# Generated by Django 6.1.1 on 2026-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=12)),
                ('wheat_weight_kg', models.FloatField()),
                ('service_type', models.CharField(choices=[('SELF', 'I will come'), ('DELIVERY', 'delivery')], default='SELF', max_length=10)),
                ('manual_location', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longtitude', models.FloatField(blank=True, null=True)),
                ('grinding_cost', models.FloatField(default=0.0)),
                ('delivery_cost', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('estimated_wait_time_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'waiting'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
