# Generated by Django 6.1.1 on 2026-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manual_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
