# Generated by Django 6.1.1 on 2026-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_manual_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
